# Generated by Django 3.0.6 on 2022-07-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_picture'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='course.Module'),
        ),
    ]
