# Generated by Django 3.0.6 on 2022-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20220728_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(default='This is somethig about this exam that this student should know. Good luck!'),
            preserve_default=False,
        ),
    ]
