# Generated by Django 3.0.6 on 2022-07-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='picture',
        ),
    ]
