# Generated by Django 3.0.6 on 2022-06-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accyear', '0001_initial'),
        ('acctype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('out_of', models.FloatField()),
                ('privacy', models.CharField(choices=[('Student', 'Student'), ('All', 'All')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gr_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accyear.GradeSubject')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='adminpanel.Result')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='acctype.Student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PreviousGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_score', to='acctype.Student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_desc', models.TextField(blank=True, null=True)),
                ('first_50', models.FloatField(blank=True)),
                ('second_desc', models.TextField(blank=True, null=True)),
                ('second_50', models.FloatField(blank=True, null=True)),
                ('third_desc', models.TextField(blank=True, null=True)),
                ('third_50', models.FloatField(blank=True, null=True)),
                ('forth_desc', models.TextField(blank=True, null=True)),
                ('forth_50', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gr_stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_score', to='accyear.GradeStudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_score', to='accyear.Subject')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('Present', 'P'), ('Absent', 'A'), ('Leave', 'L'), ('Close', 'Close')], max_length=10)),
                ('att_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendaces', to='acctype.Student')),
            ],
            options={
                'ordering': ['-att_date'],
            },
        ),
    ]
