# Generated by Django 3.0.6 on 2022-06-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acctype', '0001_initial'),
        ('accyear', '0001_initial'),
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_who', models.CharField(choices=[('All Class', 'All Class'), ('Student', 'Student')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('dscription', models.TextField()),
                ('due_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gr_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='accyear.GradeSubject')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='acctype.Student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Group', 'Group'), ('Individual', 'Individual')], max_length=10)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('chapters', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('graded', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('out_of', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gr_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accyear.GradeSubject')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
