# Generated by Django 3.0.6 on 2022-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20220629_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalscore',
            name='first_50',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
