# Generated by Django 3.0.6 on 2022-08-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_classschedule_scheduletimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='rest',
            field=models.BooleanField(default=False),
        ),
    ]
