# Generated by Django 3.0.6 on 2022-08-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acctype', '0001_initial'),
        ('accyear', '0001_initial'),
        ('adminpanel', '0008_auto_20220803_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_starts', models.DateField()),
                ('payment_ends', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['payment_starts'],
            },
        ),
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ['schedule_time']},
        ),
        migrations.AlterModelOptions(
            name='scheduletimes',
            options={'ordering': ['start']},
        ),
        migrations.CreateModel(
            name='SPPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField()),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid', to='adminpanel.SchoolPayment')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid', to='acctype.Student')),
            ],
            options={
                'ordering': ['-paid_on'],
            },
        ),
        migrations.CreateModel(
            name='SPGradeAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_payment', to='accyear.Grade')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='adminpanel.SchoolPayment')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
