# Generated by Django 3.0.6 on 2022-08-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20220805_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spgradeassociation',
            options={'ordering': ['sp']},
        ),
    ]
